// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

/*
Package gossip is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	PbNode
	PbMessage
*/
package gossip

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type State int32

const (
	State_UP      State = 1
	State_SUSPECT State = 2
	State_DOWN    State = 3
)

var State_name = map[int32]string{
	1: "UP",
	2: "SUSPECT",
	3: "DOWN",
}
var State_value = map[string]int32{
	"UP":      1,
	"SUSPECT": 2,
	"DOWN":    3,
}

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}
func (x State) String() string {
	return proto.EnumName(State_name, int32(x))
}
func (x *State) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(State_value, data, "State")
	if err != nil {
		return err
	}
	*x = State(value)
	return nil
}

type PbMessage_Type int32

const (
	PbMessage_HELLO PbMessage_Type = 1
)

var PbMessage_Type_name = map[int32]string{
	1: "HELLO",
}
var PbMessage_Type_value = map[string]int32{
	"HELLO": 1,
}

func (x PbMessage_Type) Enum() *PbMessage_Type {
	p := new(PbMessage_Type)
	*p = x
	return p
}
func (x PbMessage_Type) String() string {
	return proto.EnumName(PbMessage_Type_name, int32(x))
}
func (x *PbMessage_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PbMessage_Type_value, data, "PbMessage_Type")
	if err != nil {
		return err
	}
	*x = PbMessage_Type(value)
	return nil
}

type PbNode struct {
	Address          *string `protobuf:"bytes,1,req,name=address" json:"address,omitempty"`
	Region           *string `protobuf:"bytes,2,req,name=region" json:"region,omitempty"`
	State            *State  `protobuf:"varint,3,req,name=state,enum=gossip.State" json:"state,omitempty"`
	Version          *int32  `protobuf:"varint,4,req,name=version" json:"version,omitempty"`
	Lastseen         *int32  `protobuf:"varint,15,opt,name=lastseen" json:"lastseen,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PbNode) Reset()         { *m = PbNode{} }
func (m *PbNode) String() string { return proto.CompactTextString(m) }
func (*PbNode) ProtoMessage()    {}

func (m *PbNode) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *PbNode) GetRegion() string {
	if m != nil && m.Region != nil {
		return *m.Region
	}
	return ""
}

func (m *PbNode) GetState() State {
	if m != nil && m.State != nil {
		return *m.State
	}
	return State_UP
}

func (m *PbNode) GetVersion() int32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *PbNode) GetLastseen() int32 {
	if m != nil && m.Lastseen != nil {
		return *m.Lastseen
	}
	return 0
}

type PbMessage struct {
	Id               *uint32         `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Type             *PbMessage_Type `protobuf:"varint,2,req,name=type,enum=gossip.PbMessage_Type" json:"type,omitempty"`
	Src              *PbNode         `protobuf:"bytes,3,req,name=src" json:"src,omitempty"`
	Neighbors        []*PbNode       `protobuf:"bytes,4,rep,name=neighbors" json:"neighbors,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *PbMessage) Reset()         { *m = PbMessage{} }
func (m *PbMessage) String() string { return proto.CompactTextString(m) }
func (*PbMessage) ProtoMessage()    {}

func (m *PbMessage) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *PbMessage) GetType() PbMessage_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return PbMessage_HELLO
}

func (m *PbMessage) GetSrc() *PbNode {
	if m != nil {
		return m.Src
	}
	return nil
}

func (m *PbMessage) GetNeighbors() []*PbNode {
	if m != nil {
		return m.Neighbors
	}
	return nil
}

func init() {
	proto.RegisterEnum("gossip.State", State_name, State_value)
	proto.RegisterEnum("gossip.PbMessage_Type", PbMessage_Type_name, PbMessage_Type_value)
}
